server:
  env: "debug"
  address: "localhost"
  port: 8080
  JWTSecret: vio

db:
  port: 3306
  host: "localhost"
  name: "favani"
  user: "root"
  password: "violet81920"
  migrate: true

redis:
  enable: true
  port: 6379
  host: "localhost"
  password: "123456"
