# 替换为你自己的配置，然后重命名为 app.yaml
server:
  env: "debug"
  address: "localhost"
  port: 8080
  JWTSecret: your-secret

db:
  port: 3306
  host: "localhost"
  name: "favani"
  user: "root"
  password: "your-password"
  migrate: true

redis:
  enable: true
  port: 6379
  host: "localhost"
  password: "123456"
